#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/schoolwatch/schoolwatch /usr/bin/schoolwatch
	
	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/schoolwatch.service ]; then
			rm /etc/systemd/system/schoolwatch.service /usr/lib/systemd/system/schoolwatch.service /usr/lib/systemd/user/schoolwatch.service >/dev/null  2>&1
		fi
		version=$(python3 -V 2>&1 | grep -Po '(?<=Python )(.+)')
		parsedVersion=$(echo "${version//./}")
        mkdir -p /usr/lib/systemd/system/
		cp /usr/share/schoolwatch/files/systemd/schoolwatch.service /usr/lib/systemd/system/schoolwatch.service
		# try fix error in Ubuntu 18.04
		# Failed to reload schoolwatch.service: Unit schoolwatch.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/schoolwatch.service:10: Executable path is not absolute: pkill -f "schoolwatch --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/schoolwatch.service
		fi
		systemctl daemon-reload
		systemctl enable schoolwatch
		systemctl start schoolwatch
	fi
fi
